server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/bestidea?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
    hikari:
      connection-timeout: 3000          # 连接超时时长
      minimum-idle: 5                   # 最小连接数
      maximum-pool-size: 20             # 最大连接数
      auto-commit: true                 # 自动提交
      idle-timeout: 600000              # 连接超时最大时长
      pool-name: DataSourceHikariCP     # 连接池名称
      max-lifetime: 1800000             # 连接的生命时长
      connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379
    timeout: 1000
  devtools:
    restart:
      enabled: true
      exclude: static/**
  servlet:
    multipart:
      location: classpath:upload/


mybatis:
  type-aliases-package: com.leafych.bestideaserver.entity
  mapperLocations: classpath:mappers/*.xml
  config-location: classpath:/mybatis-config.xml








