server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql://127.0.0.1:3306/bestidea?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
  devtools:
    restart:
      enabled: true
      exclude: static/**

mybatis:
  type-aliases-package: com.leafych.bestideaserver.entity
  mapperLocations: classpath:mappers/*.xml
  config-location: classpath:/mybatis-config.xml


